### ISSUE TITLE
Needs updated to use Vue CLI 3.0 and latest version of vue-test-utils

### ISSUE THREAD

**Issue by kb-coder** [vuejs/vue-test-utils-mocha-webpack-example#12]
This sample project needs to be updated using Vue CLI 3.0 and the latest version of vue-test-utils. It's not clear how to configure mocha webpack to work with the new CLI hidden webpack.config.

**Comment by yyx990803** [comment]
The new CLI supports all of these out of the box. This demo is irrelevant for CLI 3.
