### ISSUE TITLE
please update to recent vue-loader with vueloaderplugin

### ISSUE THREAD

**Issue by LisaHS** [vuejs/vue-test-utils-mocha-webpack-example#13]
I have problems generating a correct lcov report using SFC. The source path in lcov.info is wrong.

If I use for webpack devtool: "eval", I get:
SF:C:/src/main/frontend/js/components/VueComponent.vue?vue&type=script&lang=js&

If I use for webpack devtool: "inline-source-map", I get:
SF:C:\src\main\frontend\js\components\js\components\VueComponent.vue 

The correct path is actually:
C:\src\main\frontend\js\components\VueComponent.vue

It would be very helpful to have an example using the latest vue-loader.

**Comment by LisaHS** [comment]
Updating to the new nyc-Version and to all new Babel-Versions solved the problem: 

`"@babel/core": "7.0.1", 
"@babel/register": "7.0.0", 
"babel-loader": "8.0.2", 
"babel-plugin-istanbul": "5.0.1", 
"@babel/preset-env": "7.0.0", 
"nyc": "13.0.1",`

**Comment by eddyerburgh** [comment]
Would you like to make a PR with the fix?

**Comment by eddyerburgh** [comment]
Would you like to make a PR with the fix?
